ROWS = 6
COLUMNS = 7
TOTAL_SPACES = ROWS * COLUMNS
PLAYER_ONE = 0
PLAYER_TWO = 1
EMPTY_SPACE = 2
COINS_TO_STR = {EMPTY_SPACE: ".", PLAYER_ONE: "x", PLAYER_TWO: "o"}
STR_TO_COINS = {".": EMPTY_SPACE, "x": PLAYER_ONE, "o": PLAYER_TWO}