ROWS = 6
COLUMNS = 7
EMPTY_SPACE = 0
PLAYER_ONE = 1
PLAYER_TWO = 2
COINS_TO_STR = {EMPTY_SPACE: ".", PLAYER_ONE: "x", PLAYER_TWO: "o"}
STR_TO_COINS = {".": EMPTY_SPACE, "x": PLAYER_ONE, "o": PLAYER_TWO}